version: "3.9"

services:
  postgres:
    container_name: postgres3
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=LearningApp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres-data:
